
name: Upload Python Package

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:


permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install pyenv
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"
        # source ~/.bashrc
        pyenv install 3.8.10
        pyenv global 3.8.10
        echo "================="
        python --version
        echo "================="
        python -m pip install --upgrade pip
        pip install git+https://github.com/kivy/buildozer.git
        pip install docopt
        pip install sh
        pip install kivy
        pip install kivymd
        pip install Cython==0.29.33
        pip list -v
        # export PATH="/Users/runner/.pyenv/versions/3.8.10/bin:$PATH"
        # source ~/.bashrc        
        
    - name: generate dmg
      run: |
        export PATH="/Users/runner/.pyenv/versions/3.8.10/bin:$PATH"
        buildozer -v osx debug

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          token: ${{ github.token }}
          files: /Users/runner/work/macDeskTopGadgets/macDeskTopGadgets/bin/myapp.dmg



